name: Publish release to PyPI

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build package for release
    uses: qua-platform/qua-dashboards/.github/workflows/reusable-build.yaml@main

  release:
    name: Release package to PyPi
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
          pattern: python-package-*

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
